language: c
os: linux
dist: xenial
compiler: gcc
before_script:
  - make
  - echo "Woohoo! Compiled!"

script:
  - make testgiftcardreader
  - echo "Woohoo! Program ran with normal file!"

  - |
    echo "Testing all inputs in data/*"
    for file in data/*; do
      echo "Testing $file"
      ./giftcardreader.exe 1 $file
      ./giftcardreader.exe 2 $file
    done